<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Collin Real">
<meta name="dcterms.date" content="2024-07-26">

<title>Collin Real - Data Analysis Portfolio - R Coding Exercise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Collin Real - Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assignments/market_segmentation/pca_kmeans_market_segmentation.html" rel="" target="">
 <span class="dropdown-text">Market Segmentation - PCA ^&amp; K-means Clustering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Video Processing in Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">CDC Data Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/psilosanctum/collinreal-P2-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R Coding Exercise</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Collin Real </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 26, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="loading-and-checking-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-and-checking-data">Loading and Checking Data</h2>
<section id="import-libraries" class="level3">
<h3 class="anchored" data-anchor-id="import-libraries">Import libraries</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs) <span class="co"># to import dataset</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># data aggregation</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co"># data aggregation? </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(gapminder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="help-function" class="level3">
<h3 class="anchored" data-anchor-id="help-function">Help Function</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(<span class="st">"gapminder"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-structure-overview" class="level3">
<h3 class="anchored" data-anchor-id="data-structure-overview">Data Structure Overview</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gapminder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10545 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
 $ infant_mortality: num  115.4 148.2 208 NA 59.9 ...
 $ life_expectancy : num  62.9 47.5 36 63 65.4 ...
 $ fertility       : num  6.19 7.65 7.32 4.43 3.11 4.55 4.82 3.45 2.7 5.57 ...
 $ population      : num  1636054 11124892 5270844 54681 20619075 ...
 $ gdp             : num  NA 1.38e+10 NA NA 1.08e+11 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 4 1 1 2 2 3 2 5 4 3 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 19 11 10 2 15 21 2 1 22 21 ...</code></pre>
</div>
</div>
</section>
<section id="data-summary" class="level3">
<h3 class="anchored" data-anchor-id="data-summary">Data Summary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gapminder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                country           year      infant_mortality life_expectancy
 Albania            :   57   Min.   :1960   Min.   :  1.50   Min.   :13.20  
 Algeria            :   57   1st Qu.:1974   1st Qu.: 16.00   1st Qu.:57.50  
 Angola             :   57   Median :1988   Median : 41.50   Median :67.54  
 Antigua and Barbuda:   57   Mean   :1988   Mean   : 55.31   Mean   :64.81  
 Argentina          :   57   3rd Qu.:2002   3rd Qu.: 85.10   3rd Qu.:73.00  
 Armenia            :   57   Max.   :2016   Max.   :276.90   Max.   :83.90  
 (Other)            :10203                  NA's   :1453                    
   fertility       population             gdp               continent   
 Min.   :0.840   Min.   :3.124e+04   Min.   :4.040e+07   Africa  :2907  
 1st Qu.:2.200   1st Qu.:1.333e+06   1st Qu.:1.846e+09   Americas:2052  
 Median :3.750   Median :5.009e+06   Median :7.794e+09   Asia    :2679  
 Mean   :4.084   Mean   :2.701e+07   Mean   :1.480e+11   Europe  :2223  
 3rd Qu.:6.000   3rd Qu.:1.523e+07   3rd Qu.:5.540e+10   Oceania : 684  
 Max.   :9.220   Max.   :1.376e+09   Max.   :1.174e+13                  
 NA's   :187     NA's   :185         NA's   :2972                       
             region    
 Western Asia   :1026  
 Eastern Africa : 912  
 Western Africa : 912  
 Caribbean      : 741  
 South America  : 684  
 Southern Europe: 684  
 (Other)        :5586  </code></pre>
</div>
</div>
</section>
<section id="class-functions---object-determination" class="level3">
<h3 class="anchored" data-anchor-id="class-functions---object-determination">Class Functions - Object Determination</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(gapminder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
</section>
</section>
<section id="processing-data" class="level2">
<h2 class="anchored" data-anchor-id="processing-data">Processing Data</h2>
<section id="assign-only-african-countries-to-a-new-objectvariable." class="level3">
<h3 class="anchored" data-anchor-id="assign-only-african-countries-to-a-new-objectvariable.">Assign only African countries to a new object/variable.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>africadata <span class="ot">=</span> <span class="fu">filter</span>(gapminder, continent <span class="sc">==</span> <span class="st">'Africa'</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(africadata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       country year infant_mortality life_expectancy fertility population
1      Algeria 1960            148.2           47.50      7.65   11124892
2       Angola 1960            208.0           35.98      7.32    5270844
3        Benin 1960            186.9           38.29      6.28    2431620
4     Botswana 1960            115.5           50.34      6.62     524029
5 Burkina Faso 1960            161.3           35.21      6.29    4829291
6      Burundi 1960            145.1           40.58      6.95    2786740
          gdp continent          region
1 13828152297    Africa Northern Africa
2          NA    Africa   Middle Africa
3   621797131    Africa  Western Africa
4   124460933    Africa Southern Africa
5   596612183    Africa  Western Africa
6   341126765    Africa  Eastern Africa</code></pre>
</div>
</div>
</section>
<section id="africa-data-structure-overview" class="level3">
<h3 class="anchored" data-anchor-id="africa-data-structure-overview">Africa Data Structure Overview</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africadata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 2 3 18 22 26 27 29 31 32 33 ...
 $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
 $ infant_mortality: num  148 208 187 116 161 ...
 $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...
 $ fertility       : num  7.65 7.32 6.28 6.62 6.29 6.95 5.65 6.89 5.84 6.25 ...
 $ population      : num  11124892 5270844 2431620 524029 4829291 ...
 $ gdp             : num  1.38e+10 NA 6.22e+08 1.24e+08 5.97e+08 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 11 10 20 17 20 5 10 20 10 10 ...</code></pre>
</div>
</div>
</section>
<section id="africa-summary" class="level3">
<h3 class="anchored" data-anchor-id="africa-summary">Africa Summary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africadata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         country          year      infant_mortality life_expectancy
 Algeria     :  57   Min.   :1960   Min.   : 11.40   Min.   :13.20  
 Angola      :  57   1st Qu.:1974   1st Qu.: 62.20   1st Qu.:48.23  
 Benin       :  57   Median :1988   Median : 93.40   Median :53.98  
 Botswana    :  57   Mean   :1988   Mean   : 95.12   Mean   :54.38  
 Burkina Faso:  57   3rd Qu.:2002   3rd Qu.:124.70   3rd Qu.:60.10  
 Burundi     :  57   Max.   :2016   Max.   :237.40   Max.   :77.60  
 (Other)     :2565                  NA's   :226                     
   fertility       population             gdp               continent   
 Min.   :1.500   Min.   :    41538   Min.   :4.659e+07   Africa  :2907  
 1st Qu.:5.160   1st Qu.:  1605232   1st Qu.:8.373e+08   Americas:   0  
 Median :6.160   Median :  5570982   Median :2.448e+09   Asia    :   0  
 Mean   :5.851   Mean   : 12235961   Mean   :9.346e+09   Europe  :   0  
 3rd Qu.:6.860   3rd Qu.: 13888152   3rd Qu.:6.552e+09   Oceania :   0  
 Max.   :8.450   Max.   :182201962   Max.   :1.935e+11                  
 NA's   :51      NA's   :51          NA's   :637                        
                       region   
 Eastern Africa           :912  
 Western Africa           :912  
 Middle Africa            :456  
 Northern Africa          :342  
 Southern Africa          :285  
 Australia and New Zealand:  0  
 (Other)                  :  0  </code></pre>
</div>
</div>
</section>
<section id="african-infant-mortality-object" class="level3">
<h3 class="anchored" data-anchor-id="african-infant-mortality-object">African Infant Mortality Object</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>infant_survival_rate <span class="ot">=</span> africadata <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(infant_mortality, life_expectancy)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(infant_survival_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  infant_mortality life_expectancy
1            148.2           47.50
2            208.0           35.98
3            186.9           38.29
4            115.5           50.34
5            161.3           35.21
6            145.1           40.58</code></pre>
</div>
</div>
</section>
<section id="african-infant-mortality-data-structure" class="level3">
<h3 class="anchored" data-anchor-id="african-infant-mortality-data-structure">African Infant Mortality Data Structure</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(infant_survival_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ infant_mortality: num  148 208 187 116 161 ...
 $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
</div>
</section>
<section id="african-infant-mortality-data-summary" class="level3">
<h3 class="anchored" data-anchor-id="african-infant-mortality-data-summary">African Infant Mortality Data Summary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(infant_survival_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> infant_mortality life_expectancy
 Min.   : 11.40   Min.   :13.20  
 1st Qu.: 62.20   1st Qu.:48.23  
 Median : 93.40   Median :53.98  
 Mean   : 95.12   Mean   :54.38  
 3rd Qu.:124.70   3rd Qu.:60.10  
 Max.   :237.40   Max.   :77.60  
 NA's   :226                     </code></pre>
</div>
</div>
</section>
<section id="african-mortality-object" class="level3">
<h3 class="anchored" data-anchor-id="african-mortality-object">African Mortality Object</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>african_mortality <span class="ot">=</span> africadata <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(population, life_expectancy)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(african_mortality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  population life_expectancy
1   11124892           47.50
2    5270844           35.98
3    2431620           38.29
4     524029           50.34
5    4829291           35.21
6    2786740           40.58</code></pre>
</div>
</div>
</section>
<section id="african-mortality-data-structure" class="level3">
<h3 class="anchored" data-anchor-id="african-mortality-data-structure">African Mortality Data Structure</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(african_mortality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ population     : num  11124892 5270844 2431620 524029 4829291 ...
 $ life_expectancy: num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
</div>
</section>
<section id="african-mortality-data-summary" class="level3">
<h3 class="anchored" data-anchor-id="african-mortality-data-summary">African Mortality Data Summary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(african_mortality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   population        life_expectancy
 Min.   :    41538   Min.   :13.20  
 1st Qu.:  1605232   1st Qu.:48.23  
 Median :  5570982   Median :53.98  
 Mean   : 12235961   Mean   :54.38  
 3rd Qu.: 13888152   3rd Qu.:60.10  
 Max.   :182201962   Max.   :77.60  
 NA's   :51                         </code></pre>
</div>
</div>
</section>
</section>
<section id="plotting" class="level2">
<h2 class="anchored" data-anchor-id="plotting">Plotting</h2>
<section id="life-expectancy-as-a-function-of-infant-mortality" class="level3">
<h3 class="anchored" data-anchor-id="life-expectancy-as-a-function-of-infant-mortality">Life Expectancy as a Function of Infant Mortality</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">=</span> <span class="fu">lm</span>(infant_survival_rate<span class="sc">$</span>life_expectancy <span class="sc">~</span> infant_survival_rate<span class="sc">$</span>infant_mortality)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>rsq <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) <span class="fu">summary</span>(<span class="fu">lm</span>(infant_survival_rate<span class="sc">$</span>life_expectancy <span class="sc">~</span> infant_survival_rate<span class="sc">$</span>infant_mortality))<span class="sc">$</span>r.squared</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>r_square <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">rsq</span>(obs, mod), <span class="dv">3</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(regression)$coefficients - keep to sanity check</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>coeff <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="dv">3</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>y_int <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">1</span>],<span class="dv">3</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  infant_survival_rate<span class="sc">$</span>infant_mortality,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  infant_survival_rate<span class="sc">$</span>life_expectancy,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">main=</span><span class="st">'African Life Expectancy </span><span class="sc">\n</span><span class="st"> Infant Mortality Effect'</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">'Infant Mortality'</span>,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">'Life Expectancy'</span>,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>   <span class="at">col=</span><span class="st">'blue'</span>, </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>   <span class="at">bg=</span><span class="st">'lightblue'</span>, </span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>   <span class="at">pch =</span> <span class="dv">21</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="co"># rsq_str = expression(paste("r"^"2:"))</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>rsq_str <span class="ot">=</span> <span class="st">"r2: "</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">175</span>, <span class="dv">75</span>, <span class="fu">paste0</span>(<span class="st">'y = '</span>, coeff, <span class="st">'x + '</span>, y_int), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">170</span>, <span class="dv">70</span>, <span class="fu">paste0</span>(rsq_str, r_square), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    infant_survival_rate<span class="sc">$</span>life_expectancy <span class="sc">~</span> infant_survival_rate<span class="sc">$</span>infant_mortality),</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="st">'black'</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd=</span><span class="fl">1.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="life-expectancy-as-a-function-of-population" class="level3">
<h3 class="anchored" data-anchor-id="life-expectancy-as-a-function-of-population">Life Expectancy as a Function of Population</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">=</span> <span class="fu">lm</span>(african_mortality<span class="sc">$</span>life_expectancy <span class="sc">~</span> african_mortality<span class="sc">$</span>population)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>rsq <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) <span class="fu">summary</span>(<span class="fu">lm</span>(african_mortality<span class="sc">$</span>life_expectancy <span class="sc">~</span> african_mortality<span class="sc">$</span>population))<span class="sc">$</span>r.squared</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>r_square <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">rsq</span>(obs, mod), <span class="dv">3</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(regression)$coefficients - keep to sanity check</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>coeff <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="dv">9</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>y_int <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">1</span>],<span class="dv">3</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  african_mortality<span class="sc">$</span>population,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  african_mortality<span class="sc">$</span>life_expectancy,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">main=</span><span class="st">'African Life Expectancy </span><span class="sc">\n</span><span class="st"> Population Effect'</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">'Population'</span>,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">'Life Expectancy'</span>,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="st">'blue'</span>, </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">bg=</span><span class="st">'lightblue'</span>, </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">21</span>,</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="co"># rsq_str = expression(paste("r"^"2:"))</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>rsq_str <span class="ot">=</span> <span class="st">"r2: "</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">155000000</span>, <span class="dv">75</span>, <span class="fu">paste0</span>(<span class="st">'y = '</span>, coeff, <span class="st">'x + '</span>, y_int), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">155000000</span>, <span class="dv">70</span>, <span class="fu">paste0</span>(rsq_str, r_square), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>  african_mortality<span class="sc">$</span>life_expectancy <span class="sc">~</span> african_mortality<span class="sc">$</span>population),</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span><span class="st">'black'</span>,</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="at">lwd=</span><span class="fl">1.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>** STILL NEED TO ANSWER QUESTION AT THE END OF THE PLOTTING SECTION**</p>
</section>
</section>
<section id="more-data-processing" class="level2">
<h2 class="anchored" data-anchor-id="more-data-processing">More Data Processing</h2>
<section id="missing-years-for-infant-mortality-data" class="level3">
<h3 class="anchored" data-anchor-id="missing-years-for-infant-mortality-data">Missing Years For Infant Mortality Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>miss_inf_mort_rows <span class="ot">=</span> africadata <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(infant_mortality))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(miss_inf_mort_rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            country year infant_mortality life_expectancy fertility population
1        Cape Verde 1960               NA           50.12      6.89     202316
2              Chad 1960               NA           40.95      6.25    3002596
3          Djibouti 1960               NA           45.77      6.46      83636
4 Equatorial Guinea 1960               NA           37.69      5.51     252115
5           Eritrea 1960               NA           39.03      6.90    1407631
6             Gabon 1960               NA           38.83      4.38     499189
        gdp continent         region
1        NA    Africa Western Africa
2 750173439    Africa  Middle Africa
3        NA    Africa Eastern Africa
4        NA    Africa  Middle Africa
5        NA    Africa Eastern Africa
6 887289809    Africa  Middle Africa</code></pre>
</div>
</div>
</section>
<section id="perform-year-groupby-to-identify-distinct-missing-years" class="level3">
<h3 class="anchored" data-anchor-id="perform-year-groupby-to-identify-distinct-missing-years">Perform Year Groupby to Identify Distinct Missing Years</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>miss_inf_mort_yrs <span class="ot">=</span> miss_inf_mort_rows <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(infant_mortality)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>miss_inf_mort_yrs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 3
# Groups:   year [23]
    year infant_mortality     n
   &lt;int&gt;            &lt;dbl&gt; &lt;int&gt;
 1  1960               NA    10
 2  1961               NA    17
 3  1962               NA    16
 4  1963               NA    16
 5  1964               NA    15
 6  1965               NA    14
 7  1966               NA    13
 8  1967               NA    11
 9  1968               NA    11
10  1969               NA     7
# ℹ 13 more rows</code></pre>
</div>
</div>
</section>
<section id="extract-only-year-2000-from-africadata-as-new-object" class="level3">
<h3 class="anchored" data-anchor-id="extract-only-year-2000-from-africadata-as-new-object">Extract Only Year 2000 From africadata As New Object</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>africadata2000 <span class="ot">=</span> <span class="fu">filter</span>(africadata, year <span class="sc">==</span> <span class="dv">2000</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>africadata2000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    country year infant_mortality life_expectancy fertility
1                   Algeria 2000             33.9            73.3      2.51
2                    Angola 2000            128.3            52.3      6.84
3                     Benin 2000             89.3            57.2      5.98
4                  Botswana 2000             52.4            47.6      3.41
5              Burkina Faso 2000             96.2            52.6      6.59
6                   Burundi 2000             93.4            46.7      7.06
7                  Cameroon 2000             91.9            54.3      5.62
8                Cape Verde 2000             29.1            68.4      3.70
9  Central African Republic 2000            113.6            45.3      5.45
10                     Chad 2000            105.7            51.5      7.35
11                  Comoros 2000             72.7            62.1      5.32
12         Congo, Dem. Rep. 2000            107.4            54.3      7.09
13              Congo, Rep. 2000             76.6            52.5      5.13
14            Cote d'Ivoire 2000             99.5            52.0      5.38
15                 Djibouti 2000             79.7            60.0      4.47
16                    Egypt 2000             37.0            69.7      3.31
17        Equatorial Guinea 2000            104.8            52.9      5.77
18                  Eritrea 2000             58.3            37.6      5.94
19                 Ethiopia 2000             89.5            52.1      6.53
20                    Gabon 2000             55.6            59.3      4.60
21                   Gambia 2000             63.3            63.6      5.92
22                    Ghana 2000             64.9            60.0      4.67
23                   Guinea 2000            103.1            54.2      5.94
24            Guinea-Bissau 2000            106.9            52.8      5.85
25                    Kenya 2000             66.5            55.6      5.01
26                  Lesotho 2000             84.1            50.7      4.09
27                  Liberia 2000            123.0            55.8      5.88
28                    Libya 2000             24.2            74.8      3.05
29               Madagascar 2000             69.7            59.1      5.55
30                   Malawi 2000            103.5            45.4      6.25
31                     Mali 2000            116.0            53.5      6.84
32               Mauritania 2000             76.2            63.8      5.38
33                Mauritius 2000             16.4            71.4      1.99
34                  Morocco 2000             42.2            71.5      2.70
35               Mozambique 2000            115.0            52.3      5.78
36                  Namibia 2000             49.4            54.0      4.03
37                    Niger 2000            101.1            52.4      7.73
38                  Nigeria 2000            112.0            55.2      6.10
39                   Rwanda 2000            109.2            49.2      5.90
40                  Senegal 2000             68.5            59.7      5.56
41               Seychelles 2000             12.3            70.9      2.15
42             Sierra Leone 2000            143.3            51.5      5.92
43             South Africa 2000             54.0            56.4      2.87
44                    Sudan 2000             67.8            62.4      5.44
45                Swaziland 2000             84.0            48.8      4.21
46                 Tanzania 2000             80.3            54.3      5.69
47                     Togo 2000             76.2            56.7      5.29
48                  Tunisia 2000             26.3            75.0      2.11
49                   Uganda 2000             90.0            49.1      6.87
50                   Zambia 2000             97.6            44.8      6.07
51                 Zimbabwe 2000             63.5            47.9      4.07
   population          gdp continent          region
1    31183658  54790058957    Africa Northern Africa
2    15058638   9129180361    Africa   Middle Africa
3     6949366   2254838685    Africa  Western Africa
4     1736579   5632391130    Africa Southern Africa
5    11607944   2610945549    Africa  Western Africa
6     6767073    835334807    Africa  Eastern Africa
7    15927713  10075040331    Africa   Middle Africa
8      438737    539227053    Africa  Western Africa
9     3726048    959413051    Africa   Middle Africa
10    8343321   1385050964    Africa   Middle Africa
11     547696    201900820    Africa  Eastern Africa
12   48048664   4305797176    Africa   Middle Africa
13    3109269   3219893817    Africa   Middle Africa
14   16517948  10417006096    Africa  Western Africa
15     722562    551230862    Africa  Eastern Africa
16   68334905  99838540997    Africa Northern Africa
17     530896   1254223037    Africa   Middle Africa
18    3535156    633600000    Africa  Eastern Africa
19   66443603   8179533779    Africa  Eastern Africa
20    1231548   5067838984    Africa   Middle Africa
21    1228863    786665264    Africa  Western Africa
22   18824994   4977488790    Africa  Western Africa
23    8799165   3112362568    Africa  Western Africa
24    1315455    215455490    Africa  Western Africa
25   31065820  12691278914    Africa  Eastern Africa
26    1856225    745832990    Africa Southern Africa
27    2891968    529064647    Africa  Western Africa
28    5337264  33896600871    Africa Northern Africa
29   15744811   3877575177    Africa  Eastern Africa
30   11193230   1743506520    Africa  Eastern Africa
31   11046926   2422469641    Africa  Western Africa
32    2711421   1293653473    Africa  Western Africa
33    1185143   4582562398    Africa  Eastern Africa
34   28950553  37020609825    Africa Northern Africa
35   18264536   4248747769    Africa  Eastern Africa
36    1897953   3908501441    Africa Southern Africa
37   11224523   1798365123    Africa  Western Africa
38  122876723  45983449593    Africa  Western Africa
39    8021875   1734921293    Africa  Eastern Africa
40    9860578   4691828357    Africa  Western Africa
41      81154    614879765    Africa  Eastern Africa
42    4060709    635876870    Africa  Western Africa
43   44896856 132877648091    Africa Southern Africa
44   28079664  12366140066    Africa Northern Africa
45    1063715   1524452437    Africa Southern Africa
46   33991590  10185786171    Africa  Eastern Africa
47    4874735   1294243543    Africa  Western Africa
48    9699192  21473261837    Africa Northern Africa
49   23757636   6193246632    Africa  Eastern Africa
50   10585220   3237716325    Africa  Eastern Africa
51   12499981   6689957610    Africa  Eastern Africa</code></pre>
</div>
</div>
</section>
<section id="africadata2000-data-structure" class="level3">
<h3 class="anchored" data-anchor-id="africadata2000-data-structure">africadata2000 Data Structure</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africadata2000)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   51 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 2 3 18 22 26 27 29 31 32 33 ...
 $ year            : int  2000 2000 2000 2000 2000 2000 2000 2000 2000 2000 ...
 $ infant_mortality: num  33.9 128.3 89.3 52.4 96.2 ...
 $ life_expectancy : num  73.3 52.3 57.2 47.6 52.6 46.7 54.3 68.4 45.3 51.5 ...
 $ fertility       : num  2.51 6.84 5.98 3.41 6.59 7.06 5.62 3.7 5.45 7.35 ...
 $ population      : num  31183658 15058638 6949366 1736579 11607944 ...
 $ gdp             : num  5.48e+10 9.13e+09 2.25e+09 5.63e+09 2.61e+09 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 11 10 20 17 20 5 10 20 10 10 ...</code></pre>
</div>
</div>
</section>
<section id="africadata2000-data-summary" class="level3">
<h3 class="anchored" data-anchor-id="africadata2000-data-summary">africadata2000 Data Summary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africadata2000)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         country        year      infant_mortality life_expectancy
 Algeria     : 1   Min.   :2000   Min.   : 12.30   Min.   :37.60  
 Angola      : 1   1st Qu.:2000   1st Qu.: 60.80   1st Qu.:51.75  
 Benin       : 1   Median :2000   Median : 80.30   Median :54.30  
 Botswana    : 1   Mean   :2000   Mean   : 78.93   Mean   :56.36  
 Burkina Faso: 1   3rd Qu.:2000   3rd Qu.:103.30   3rd Qu.:60.00  
 Burundi     : 1   Max.   :2000   Max.   :143.30   Max.   :75.00  
 (Other)     :45                                                  
   fertility       population             gdp               continent 
 Min.   :1.990   Min.   :    81154   Min.   :2.019e+08   Africa  :51  
 1st Qu.:4.150   1st Qu.:  2304687   1st Qu.:1.274e+09   Americas: 0  
 Median :5.550   Median :  8799165   Median :3.238e+09   Asia    : 0  
 Mean   :5.156   Mean   : 15659800   Mean   :1.155e+10   Europe  : 0  
 3rd Qu.:5.960   3rd Qu.: 17391242   3rd Qu.:8.654e+09   Oceania : 0  
 Max.   :7.730   Max.   :122876723   Max.   :1.329e+11                
                                                                      
                       region  
 Eastern Africa           :16  
 Western Africa           :16  
 Middle Africa            : 8  
 Northern Africa          : 6  
 Southern Africa          : 5  
 Australia and New Zealand: 0  
 (Other)                  : 0  </code></pre>
</div>
</div>
</section>
</section>
<section id="more-plotting" class="level2">
<h2 class="anchored" data-anchor-id="more-plotting">More Plotting</h2>
<section id="create-the-same-plots-for-africadata2000-object" class="level3">
<h3 class="anchored" data-anchor-id="create-the-same-plots-for-africadata2000-object">Create The Same Plots For africadata2000 Object</h3>
<section id="filter-new-object-to-create-graph-datasets-12" class="level4">
<h4 class="anchored" data-anchor-id="filter-new-object-to-create-graph-datasets-12">Filter New Object to Create Graph Datasets (1/2)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>african_mortality2000 <span class="ot">=</span> africadata2000 <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(population, life_expectancy)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(african_mortality2000)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  population life_expectancy
1   31183658            73.3
2   15058638            52.3
3    6949366            57.2
4    1736579            47.6
5   11607944            52.6
6    6767073            46.7</code></pre>
</div>
</div>
</section>
<section id="filter-new-object-to-create-graph-datasets-22" class="level4">
<h4 class="anchored" data-anchor-id="filter-new-object-to-create-graph-datasets-22">Filter New Object to Create Graph Datasets (2/2)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>infant_survival_rate2000 <span class="ot">=</span> africadata2000 <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(infant_mortality, life_expectancy)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(african_mortality2000)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  population life_expectancy
1   31183658            73.3
2   15058638            52.3
3    6949366            57.2
4    1736579            47.6
5   11607944            52.6
6    6767073            46.7</code></pre>
</div>
</div>
</section>
<section id="infant-mortality-effect" class="level4">
<h4 class="anchored" data-anchor-id="infant-mortality-effect">Infant Mortality Effect</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">=</span> <span class="fu">lm</span>(infant_survival_rate2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> infant_survival_rate2000<span class="sc">$</span>infant_mortality)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>rsq <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) <span class="fu">summary</span>(<span class="fu">lm</span>(infant_survival_rate2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> infant_survival_rate2000<span class="sc">$</span>infant_mortality))<span class="sc">$</span>r.squared</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>r_square <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">rsq</span>(obs, mod), <span class="dv">3</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(regression)$coefficients - keep to sanity check</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>coeff <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="dv">3</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>y_int <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">1</span>],<span class="dv">3</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  infant_survival_rate2000<span class="sc">$</span>infant_mortality,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  infant_survival_rate2000<span class="sc">$</span>life_expectancy,</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">main=</span><span class="st">'African Life Expectancy </span><span class="sc">\n</span><span class="st"> Infant Mortality Effect'</span>,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">'Infant Mortality'</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">'Life Expectancy'</span>,</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>   <span class="at">col=</span><span class="st">'blue'</span>, </span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>   <span class="at">bg=</span><span class="st">'lightblue'</span>, </span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>   <span class="at">pch =</span> <span class="dv">21</span>,</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a><span class="co"># rsq_str = expression(paste("r"^"2:"))</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>rsq_str <span class="ot">=</span> <span class="st">"r2: "</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">130</span>, <span class="dv">75</span>, <span class="fu">paste0</span>(<span class="st">'y = '</span>, coeff, <span class="st">'x + '</span>, y_int), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">130</span>, <span class="dv">73</span>, <span class="fu">paste0</span>(rsq_str, r_square), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>    infant_survival_rate2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> infant_survival_rate2000<span class="sc">$</span>infant_mortality),</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="st">'black'</span>,</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd=</span><span class="fl">1.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="population-effect" class="level4">
<h4 class="anchored" data-anchor-id="population-effect">Population Effect</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">=</span> <span class="fu">lm</span>(african_mortality2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> african_mortality2000<span class="sc">$</span>population)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>rsq <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) <span class="fu">summary</span>(<span class="fu">lm</span>(african_mortality2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> african_mortality2000<span class="sc">$</span>population))<span class="sc">$</span>r.squared</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>r_square <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">rsq</span>(obs, mod), <span class="dv">3</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(regression)$coefficients - keep to sanity check</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>coeff <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="dv">9</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>y_int <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(regression)<span class="sc">$</span>coefficients[<span class="dv">1</span>],<span class="dv">3</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  african_mortality2000<span class="sc">$</span>population,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  african_mortality2000<span class="sc">$</span>life_expectancy,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">main=</span><span class="st">'African Life Expectancy </span><span class="sc">\n</span><span class="st"> Population Effect'</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">'Population'</span>,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">'Life Expectancy'</span>,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="st">'blue'</span>, </span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">bg=</span><span class="st">'lightblue'</span>, </span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">21</span>,</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a><span class="co"># rsq_str = expression(paste("r"^"2:"))</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>rsq_str <span class="ot">=</span> <span class="st">"r2: "</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">110000000</span>, <span class="dv">75</span>, <span class="fu">paste0</span>(<span class="st">'y = '</span>, coeff, <span class="st">'x + '</span>, y_int), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">110000000</span>, <span class="dv">73</span>, <span class="fu">paste0</span>(rsq_str, r_square), <span class="at">cex=</span><span class="fl">0.75</span>)</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>  african_mortality2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> african_mortality2000<span class="sc">$</span>population),</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span><span class="st">'black'</span>,</span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a><span class="at">lwd=</span><span class="fl">1.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="simple-model-fits" class="level2">
<h2 class="anchored" data-anchor-id="simple-model-fits">Simple Model Fits</h2>
<section id="fit-life-expectancy-to-infant-mortality" class="level3">
<h3 class="anchored" data-anchor-id="fit-life-expectancy-to-infant-mortality">Fit Life Expectancy to Infant Mortality</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">=</span> <span class="fu">lm</span>(infant_survival_rate2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> infant_survival_rate2000<span class="sc">$</span>infant_mortality)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = infant_survival_rate2000$life_expectancy ~ infant_survival_rate2000$infant_mortality)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.6651  -3.7087   0.9914   4.0408   8.6817 

Coefficients:
                                          Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                               71.29331    2.42611  29.386  &lt; 2e-16
infant_survival_rate2000$infant_mortality -0.18916    0.02869  -6.594 2.83e-08
                                             
(Intercept)                               ***
infant_survival_rate2000$infant_mortality ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.221 on 49 degrees of freedom
Multiple R-squared:  0.4701,    Adjusted R-squared:  0.4593 
F-statistic: 43.48 on 1 and 49 DF,  p-value: 2.826e-08</code></pre>
</div>
</div>
</section>
<section id="fit-life-expectancy-to-population" class="level3">
<h3 class="anchored" data-anchor-id="fit-life-expectancy-to-population">Fit Life Expectancy to Population</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">=</span> <span class="fu">lm</span>(african_mortality2000<span class="sc">$</span>life_expectancy <span class="sc">~</span> african_mortality2000<span class="sc">$</span>population)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = african_mortality2000$life_expectancy ~ african_mortality2000$population)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.429  -4.602  -2.568   3.800  18.802 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      5.593e+01  1.468e+00  38.097   &lt;2e-16 ***
african_mortality2000$population 2.756e-08  5.459e-08   0.505    0.616    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.524 on 49 degrees of freedom
Multiple R-squared:  0.005176,  Adjusted R-squared:  -0.01513 
F-statistic: 0.2549 on 1 and 49 DF,  p-value: 0.6159</code></pre>
</div>
</div>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>Our fit1 model’s (i.e.&nbsp;fit life expectancy to infant mortality) independent variable has a p-value less than the significance level, so we reject the null hypothesis and conclude that infant mortality has a significant effect on life expectancy. For every infant death, life expectancy reduces by 0.18916 Our fit2 model’s (i.e.&nbsp;fit life expectancy to population) independent variable has a p-value greater than the significance level, so we do not reject the null hypothesis and conclude that population does not have a significant effect on life expectancy.</p>
</section>
</section>
<section id="this-section-contributed-by-seth-harris." class="level3">
<h3 class="anchored" data-anchor-id="this-section-contributed-by-seth-harris."><strong>This section contributed by SETH HARRIS.</strong></h3>
<ul>
<li><p><strong>Loading and Exploring the Dataset</strong>:</p>
<ul>
<li><p>Loaded the <code>dslabs</code> package and the <code>trump_tweets</code> dataset.</p></li>
<li><p>Explored the dataset using <code>str()</code>, <code>summary()</code>, and <code>head()</code> functions.</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dslabs package</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the trump_tweets dataset</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"trump_tweets"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Explore the dataset</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(trump_tweets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   20761 obs. of  8 variables:
 $ source                 : chr  "Twitter Web Client" "Twitter Web Client" "Twitter Web Client" "Twitter Web Client" ...
 $ id_str                 : chr  "6971079756" "6312794445" "6090839867" "5775731054" ...
 $ text                   : chr  "From Donald Trump: Wishing everyone a wonderful holiday &amp; a happy, healthy, prosperous New Year. Let’s think li"| __truncated__ "Trump International Tower in Chicago ranked 6th tallest building in world by Council on Tall Buildings &amp; Urban "| __truncated__ "Wishing you and yours a very Happy and Bountiful Thanksgiving!" "Donald Trump Partners with TV1 on New Reality Series Entitled, Omarosa's Ultimate Merger: http://tinyurl.com/yk5m3lc" ...
 $ created_at             : POSIXct, format: "2009-12-23 12:38:18" "2009-12-03 14:39:09" ...
 $ retweet_count          : int  28 33 13 5 7 4 2 4 1 22 ...
 $ in_reply_to_user_id_str: chr  NA NA NA NA ...
 $ favorite_count         : int  12 6 11 3 6 5 2 10 4 30 ...
 $ is_retweet             : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(trump_tweets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    source             id_str              text          
 Length:20761       Length:20761       Length:20761      
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
   created_at                     retweet_count    in_reply_to_user_id_str
 Min.   :2009-05-04 13:54:25.00   Min.   :     0   Length:20761           
 1st Qu.:2013-02-13 14:15:54.00   1st Qu.:    34   Class :character       
 Median :2014-05-03 07:07:38.00   Median :   264   Mode  :character       
 Mean   :2014-08-02 16:29:32.18   Mean   :  3854                          
 3rd Qu.:2016-02-13 20:17:51.00   3rd Qu.:  3267                          
 Max.   :2018-01-01 08:37:52.00   Max.   :369530                          
 favorite_count   is_retweet     
 Min.   :     0   Mode :logical  
 1st Qu.:    22   FALSE:20761    
 Median :   173                  
 Mean   : 13591                  
 3rd Qu.:  8573                  
 Max.   :633253                  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(trump_tweets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              source     id_str
1 Twitter Web Client 6971079756
2 Twitter Web Client 6312794445
3 Twitter Web Client 6090839867
4 Twitter Web Client 5775731054
5 Twitter Web Client 5364614040
6 Twitter Web Client 5203117820
                                                                                                                                        text
1       From Donald Trump: Wishing everyone a wonderful holiday &amp; a happy, healthy, prosperous New Year. Let’s think like champions in 2010!
2 Trump International Tower in Chicago ranked 6th tallest building in world by Council on Tall Buildings &amp; Urban Habitat http://bit.ly/sqvQq
3                                                                             Wishing you and yours a very Happy and Bountiful Thanksgiving!
4                       Donald Trump Partners with TV1 on New Reality Series Entitled, Omarosa's Ultimate Merger: http://tinyurl.com/yk5m3lc
5                         --Work has begun, ahead of schedule, to build the greatest golf course in history: Trump International – Scotland.
6              --From Donald Trump: "Ivanka and Jared’s wedding was spectacular, and they make a beautiful couple. I’m a very proud father."
           created_at retweet_count in_reply_to_user_id_str favorite_count
1 2009-12-23 12:38:18            28                    &lt;NA&gt;             12
2 2009-12-03 14:39:09            33                    &lt;NA&gt;              6
3 2009-11-26 14:55:38            13                    &lt;NA&gt;             11
4 2009-11-16 16:06:10             5                    &lt;NA&gt;              3
5 2009-11-02 09:57:56             7                    &lt;NA&gt;              6
6 2009-10-27 10:31:48             4                    &lt;NA&gt;              5
  is_retweet
1      FALSE
2      FALSE
3      FALSE
4      FALSE
5      FALSE
6      FALSE</code></pre>
</div>
</div>
<p>After reviewing the data sets available, I selected the “trump_tweets” dataset for further exploration. This data set contains all tweets from Donald Trump’s Twitter account from 2009 to 2017. Additionally, the results of a sentiment analysis, conducted on tweets from the campaign period (2015-06-17 to 2016-11-08), are included in sentiment_counts. The goal of exploring the trump_tweets dataset is to analyze and understand patterns and trends in the tweets made by former U.S. President Donald Trump. This analysis can provide insights into the topics he tweeted about, the frequency and timing of his tweets, the sentiment expressed in his tweets, and how his tweeting behavior changed over time. By examining this dataset, we can gain a better understanding of his communication strategy on social media and its potential impact on public opinion and political discourse.</p>
<p><strong>Data Cleaning and Processing</strong>:</p>
<ul>
<li><p>Removed rows with missing values using <code>na.omit()</code>.</p></li>
<li><p>Converted the <code>created_at</code> column to Date format.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Do any processing/cleaning (e.g., removing rows with missing values)</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>trump_tweets_clean <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(trump_tweets) <span class="co"># Remove rows with missing values</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the date column to Date format</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>trump_tweets_clean<span class="sc">$</span>created_at <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(trump_tweets_clean<span class="sc">$</span>created_at)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Exploratory Data Analysis</strong>:</p>
<ul>
<li>Created a histogram plot to visualize the number of tweets over time.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a few exploratory figures</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the number of tweets over time</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trump_tweets_clean, <span class="fu">aes</span>(<span class="at">x =</span> created_at)) <span class="sc">+</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Trump Tweets Over Time"</span>, <span class="at">x =</span> <span class="st">"Date"</span>, <span class="at">y =</span> <span class="st">"Number of Tweets"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finding: This plot shows the distribution of Trump's tweets over time. We can see spikes in activity around certain periods, indicating increased tweeting during those times.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From the plot “Number of Trump Tweets Over Time,” we observe a few key trends:</p>
<ol type="1">
<li><strong>Peak Activity:</strong> There is a significant peak in tweet activity around the year 2013, indicating a period when Trump was highly active on Twitter.</li>
<li><strong>Fluctuations:</strong> There are notable fluctuations in tweet frequency over time, with periods of high and low activity.</li>
<li><strong>Drop in Activity:</strong> After 2014, there is a marked decline in tweet frequency, with very few tweets observed after 2016.</li>
</ol>
<p>These trends can be indicative of changes in Trump’s social media strategy or other external factors influencing his tweet activity.</p>
<p><strong>Exploratory Data Analysis</strong>:</p>
<ul>
<li>Created a bar plot to visualize the distribution of tweet sources.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the distribution of tweet sources</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trump_tweets_clean, <span class="fu">aes</span>(<span class="at">x =</span> source)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Trump Tweet Sources"</span>, <span class="at">x =</span> <span class="st">"Source"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finding: This plot shows the different sources from which Trump tweeted. It gives us an idea of the platforms he used most frequently for tweeting.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Based on the plot above “Distribution of Trump Tweet Sources,” we can observe the following:</p>
<ol type="1">
<li><strong>Twitter Web Client</strong> is the most frequently used source, with a count exceeding 1500 tweets.</li>
<li><strong>Twitter for Android</strong> is the second most common source, with around 500 tweets.</li>
<li>Other sources like <strong>TweetDeck</strong>, <strong>TwitLonger Beta</strong>, and <strong>Twitter for iPhone</strong> have a much lower count.</li>
<li>The plot also includes less frequently used sources like <strong>Mobile Web (M5)</strong>, <strong>Twitter for BlackBerry</strong>, <strong>Twitter for iPad</strong>, and <strong>Twitter QandA</strong>.</li>
</ol>
<p>This distribution indicates that the majority of tweets were posted using the Twitter Web Client and Android platforms.</p>
<p><strong>Statistical Modeling</strong>:</p>
<ul>
<li><p>Performed linear regression to analyze the relationship between the number of retweets and favorites.</p></li>
<li><p>Performed linear regression to analyze the relationship between tweet length and the number of favorites.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run some simple statistical models</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 1: Linear regression of the number of favorites based on the number of retweets</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(favorite_count <span class="sc">~</span> retweet_count, <span class="at">data =</span> trump_tweets_clean)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = favorite_count ~ retweet_count, data = trump_tweets_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-119669    -136    -131    -128   31975 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   128.44252   68.56449   1.873   0.0611 .  
retweet_count   3.38915    0.03283 103.220   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3361 on 2440 degrees of freedom
Multiple R-squared:  0.8137,    Adjusted R-squared:  0.8136 
F-statistic: 1.065e+04 on 1 and 2440 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finding: This model examines the relationship between the number of retweets and the number of favorites. The summary provides information on the strength and significance of this relationship.</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: Linear regression of the number of favorites based on the length of the tweet</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>trump_tweets_clean<span class="sc">$</span>text_length <span class="ot">&lt;-</span> <span class="fu">nchar</span>(trump_tweets_clean<span class="sc">$</span>text)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(favorite_count <span class="sc">~</span> text_length, <span class="at">data =</span> trump_tweets_clean)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = favorite_count ~ text_length, data = trump_tweets_clean)

Residuals:
   Min     1Q Median     3Q    Max 
 -6007  -1475    -73    468 100932 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1763.260    256.052  -6.886 7.26e-12 ***
text_length    54.012      4.001  13.500  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7511 on 2440 degrees of freedom
Multiple R-squared:  0.0695,    Adjusted R-squared:  0.06912 
F-statistic: 182.2 on 1 and 2440 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finding: This model examines the relationship between the length of a tweet and the number of favorites. The summary provides insights into whether longer tweets tend to receive more favorites.</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Report the results from the models</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Model 1: Linear regression of the number of favorites based on the number of retweets</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model 1: Linear regression of the number of favorites based on the number of retweets</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(model1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = favorite_count ~ retweet_count, data = trump_tweets_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-119669    -136    -131    -128   31975 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   128.44252   68.56449   1.873   0.0611 .  
retweet_count   3.38915    0.03283 103.220   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3361 on 2440 degrees of freedom
Multiple R-squared:  0.8137,    Adjusted R-squared:  0.8136 
F-statistic: 1.065e+04 on 1 and 2440 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Model 2: Linear regression of the number of favorites based on the length of the tweet</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model 2: Linear regression of the number of favorites based on the length of the tweet</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = favorite_count ~ text_length, data = trump_tweets_clean)

Residuals:
   Min     1Q Median     3Q    Max 
 -6007  -1475    -73    468 100932 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1763.260    256.052  -6.886 7.26e-12 ***
text_length    54.012      4.001  13.500  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7511 on 2440 degrees of freedom
Multiple R-squared:  0.0695,    Adjusted R-squared:  0.06912 
F-statistic: 182.2 on 1 and 2440 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="model-1-linear-regression-of-the-number-of-favorites-based-on-the-number-of-retweets" class="level3">
<h3 class="anchored" data-anchor-id="model-1-linear-regression-of-the-number-of-favorites-based-on-the-number-of-retweets">Model 1: Linear regression of the number of favorites based on the number of retweets</h3>
<p><strong>Summary</strong>: - <strong>Intercept</strong>: 128.44 (p = 0.0611) - <strong>Slope (retweet_count)</strong>: 3.39 (p &lt; 2e-16)</p>
<p><strong>Findings</strong>: - Strong positive relationship between retweets and favorites. - High R-squared value (0.8137), indicating 81.37% of the variability in favorites is explained by retweets. - Significant model (p-value &lt; 2.2e-16).</p>
</section>
<section id="model-2-linear-regression-of-the-number-of-favorites-based-on-the-length-of-the-tweet" class="level3">
<h3 class="anchored" data-anchor-id="model-2-linear-regression-of-the-number-of-favorites-based-on-the-length-of-the-tweet">Model 2: Linear regression of the number of favorites based on the length of the tweet</h3>
<p><strong>Summary</strong>: - <strong>Intercept</strong>: -1763.26 (p &lt; 2e-16) - <strong>Slope (text_length)</strong>: 54.01 (p &lt; 2e-16)</p>
<p><strong>Findings</strong>: - Positive relationship between tweet length and favorites. - Low R-squared value (0.0695), indicating 6.95% of the variability in favorites is explained by tweet length. - Significant model (p-value &lt; 2.2e-16).</p>
</section>
<section id="comments-on-findings" class="level3">
<h3 class="anchored" data-anchor-id="comments-on-findings">Comments on Findings:</h3>
<ul>
<li><strong>Model 1</strong>: The number of retweets is a strong predictor of the number of favorites, with a high R-squared value and statistically significant coefficients. This suggests that tweets with higher retweets tend to receive more favorites.</li>
<li><strong>Model 2</strong>: The length of the tweet has a weaker relationship with the number of favorites, as indicated by the lower R-squared value. While the model is statistically significant, it explains less of the variability in the number of favorites compared to retweets.</li>
</ul>
<p>These findings suggest that while both retweets and tweet length can influence the number of favorites, retweets are a much stronger predictor.</p>
<p><strong>Reporting Findings</strong>:</p>
<ul>
<li>Analyzed and reported the results of the linear regression models, highlighting key statistics and the significance of the predictors.</li>
</ul>
<p>By following these steps, we were able to gain insights into the patterns and predictors of tweet engagement in the Trump_Tweets dataset.</p>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion</h3>
<p>The analysis of the Trump Tweets dataset reveals several interesting insights:</p>
<ol type="1">
<li><p><strong>Tweet Frequency Over Time</strong>: The histogram plot shows a significant increase in the number of tweets around mid-2013, with a peak and subsequent decline by early 2014. This trend may correlate with specific events or increased activity during that period.</p></li>
<li><p><strong>Tweet Sources</strong>: The majority of Trump’s tweets were sent from the “Twitter Web Client,” followed by “Twitter for Android.” This suggests a preference for these platforms.</p></li>
<li><p><strong>Statistical Models</strong>:</p>
<ul>
<li><strong>Model 1</strong>: There is a strong positive relationship between the number of retweets and the number of favorites, with a high R-squared value of 0.8137. This indicates that retweets are a strong predictor of favorites.</li>
<li><strong>Model 2</strong>: The length of the tweet also positively correlates with the number of favorites but to a much lesser extent, with an R-squared value of 0.0695. While statistically significant, tweet length explains much less variability in favorites compared to retweets.</li>
</ul></li>
</ol>
<p>In summary, the number of retweets is a strong indicator of the popularity of Trump’s tweets, significantly more so than the length of the tweet. This analysis provides insights into the factors influencing the engagement levels of tweets from this dataset.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>